name: mobile_app_flutter_redux
description: Mobile App Example in Flutter and Redux
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async_redux: ^26.0.0
  align_positioned: ^5.0.1
  animated_size_and_fade: ^5.1.1
  assorted_layout_widgets: ^11.0.0
  fast_immutable_collections: ^11.1.0
  matrix4_transform: ^4.0.1
  i18n_extension: ^15.1.0
  bdd_framework: ^4.0.5
  weak_map: ^4.0.1
  themed: ^8.1.0
  animations: ^2.0.11
  characters: ^1.4.0
  collection: ^1.19.1
  crypto: ^3.0.3
  flutter_svg: ^2.0.9
  http: ^1.1.2
  intl: ^0.20.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
